- name: Check for Keybase
  command: "keybase -v"
  ignore_errors: true
  register: keybase_result

- name: Install Keybase (Debian)
  when: ansible_os_family == "Debian" and keybase_result.rc != 0
  include: keybase_debian.yml

- name: Install Keybase (RedHat)
  when: ansible_os_family == "RedHat" and keybase_result.rc != 0
  include: keybase_redhat.yml
